name: TEste com robot framework

on: [push]

jobs:
  run_automation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependecies
      env:
        PYTHON_VERSION: "3.10"
      run: |
        py_version=$PYTHON_VERSION
        sudo apt update
        sudo apt install software-properties-common
        sudo add-apt-repository -y ppa:deadsnakes/ppa
        sudo apt update
        sudo apt install python"$py_version"
        sudo apt install -y nodejs
    - name: Verify Version
      run: |
          python --version
          nodejs -v
          npm --version
          aws --version
    - name: Install libraries for robot
      run: |
          pip install -U pip
          pip install -U robotframework-csvlibrary
    - name: Run Tests
      run: |
            mkdir results
            robot -d ./reports ./test-case
    - name: Upload test results
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: reports
        path: reports
        
  generate_report:
        if: always()
        needs: [run_automation] 
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Download reports
          uses: actions/download-artifact@v1
          with:
            name: reports
        - name: Send report to commit
          uses: joonvena/robotframework-reporter-action@v2
          with:
            gh_access_token: ${{ secrets.GITHUB_TOKEN }}
